export const GET_SYSTEM_REQUEST = "GET_SYSTEM_REQUEST";
export const GET_SYSTEM_SUCCESS = "GET_SYSTEM_SUCCESS";
export const GET_SYSTEM_ERROR = "GET_SYSTEM_ERROR";

export const GET_DARKMODE = "GET_DARKMODE";
export const SET_DARKMODE = "SET_DARKMODE";
