export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_ERROR = "GET_USER_ERROR";

export const GET_SYSTEM_REQUEST = "GET_SYSTEM_REQUEST";
export const GET_SYSTEM_SUCCESS = "GET_SYSTEM_SUCCESS";
export const GET_SYSTEM_ERROR = "GET_SYSTEM_ERROR";

export const GET_DARKMODE = "GET_DARKMODE";
